// highlight.js
// The highlighting interaction: dragging across text draws an underline;
// when the cursor leaves the paragraph mid-stroke, the last underlined word
// becomes a circle and a stroke flows out toward the cursor; if the cursor
// then rests, an annotation textarea appears.
//
// State machine:
//   idle → drawing            (mousedown on a grapheme span)
//   drawing → drawing         (mousemove inside same paragraph)
//   drawing → idle            (mouseup → push underline signal)
//   drawing → transitioning   (mousemove leaves the paragraph rect)
//   transitioning → annotating(cursor still ~600ms → textarea appears)
//   annotating → idle         (Enter or blur → push annotation signal)
//
// Same-session continuity: underline and annotation generated by one drag
// share the same highlight_session_id so AI can read the sequence as a unit.

import { pushSignal, setTrailEnabled, setGesturesEnabled } from "./signals.js";
import {
  getCursorFromPoint,
  charIndexToCursor,
  getCharRangeBBox,
} from "./pretext_helpers.js";

const SVG_NS = "http://www.w3.org/2000/svg";
const ANNOTATE_DELAY_MS = 600;

let state = "idle";
let session = null;
let inkLayer = null;
let annotationHost = null;

export function initHighlight() {
  inkLayer = document.getElementById("ink-layer");
  annotationHost = document.getElementById("annotation-host");
  if (!inkLayer || !annotationHost) return;

  document.addEventListener("mousedown", onMouseDown);
  document.addEventListener("mousemove", onMouseMove);
  document.addEventListener("mouseup", onMouseUp);
  // Defensive: if the window loses focus mid-drag, drop state cleanly.
  window.addEventListener("blur", () => {
    if (state === "drawing") finishUnderline();
    else if (state !== "idle") cleanupSession();
  });

  initPencilCursor();
}

// Pencil emoji cursor on hover. Per-span class application so the cursor
// rule lands on a single, specific selector — no body-level cascade, no
// inheritance ambiguity from the trail's per-frame SVG churn.
//
// Hit detection: e.target.closest() with an elementsFromPoint fallback so
// micro-gaps between adjacent inline spans don't drop the cursor.
//
// State-aware:
//   - idle: only show pencil when the mouse is in the bottom 30% of a glyph
//   - drawing: always show pencil on whichever span the mouse is over (the
//     user is dragging the pen — the cursor should follow, not vanish)
//   - transitioning / annotating: clear (mouse is off-text or the textarea
//     owns the interaction)
function initPencilCursor() {
  let activeSpan = null;
  const setActiveSpan = (span) => {
    if (activeSpan === span) return;
    if (activeSpan) activeSpan.classList.remove("pencil-cursor");
    if (span) span.classList.add("pencil-cursor");
    activeSpan = span;
  };
  const findSpan = (e) => {
    const target = e.target instanceof Element ? e.target : null;
    let span = target ? target.closest("[data-char-index]") : null;
    if (!span) {
      const stack = document.elementsFromPoint(e.clientX, e.clientY);
      span =
        stack.find((el) => el.matches && el.matches("[data-char-index]")) ||
        null;
    }
    return span;
  };
  document.addEventListener("mousemove", (e) => {
    if (state === "drawing") {
      // Follow the drag with the pencil cursor on whichever span the
      // pointer currently sits over.
      setActiveSpan(findSpan(e));
      return;
    }
    if (state !== "idle") {
      setActiveSpan(null);
      return;
    }
    const span = findSpan(e);
    if (!span) {
      setActiveSpan(null);
      return;
    }
    const rect = span.getBoundingClientRect();
    if (rect.height <= 0) {
      setActiveSpan(null);
      return;
    }
    const relY = (e.clientY - rect.top) / rect.height;
    setActiveSpan(relY >= 0.7 ? span : null);
  });
}

// ---------- mouse handlers ----------

function onMouseDown(e) {
  if (state !== "idle") return;
  if (e.button !== 0) return;
  const target = e.target;
  if (!(target instanceof Element)) return;
  if (!target.closest("[data-char-index]")) return;
  // Don't start when clicking inside an open annotation, toolbar, dashboard.
  if (target.closest(".annotation-box, .toolbar, .dashboard")) return;

  const hit = getCursorFromPoint(e.clientX, e.clientY);
  if (!hit) return;

  const id = uuid();
  session = {
    id,
    paragraphId: hit.paragraphId,
    paragraphEl: document.querySelector(
      `[data-paragraph-id="${hit.paragraphId}"]`,
    ),
    startChar: hit.charIndex,
    // Chain: contiguous run of visited chars that includes startChar.
    // Only chars the cursor's path actually crossed are added to visitedChars,
    // and only those adjacent to the chain ends extend it (the "chain rule").
    chainLo: hit.charIndex,
    chainHi: hit.charIndex,
    visitedChars: new Set([hit.charIndex]),
    prevX: e.clientX,
    prevY: e.clientY,
    startCursor: hit.cursor,
    startTime: performance.now(),
    lastAddT: performance.now(),
    underlinedSpans: new Set(),
    // transition / annotation phase state
    anchorCircle: null,
    anchorCenter: null,
    inkPath: null,
    transitionT: 0,
    lastMoveT: 0,
    idleTimer: null,
    annotationBox: null,
    textareaAppearedT: 0,
    anchorWord: null,
  };
  // Lock passive signal collectors so they don't fight the highlight stroke.
  setTrailEnabled(false);
  setGesturesEnabled(false);
  state = "drawing";
  applyUnderline();
  e.preventDefault();
}

function onMouseMove(e) {
  if (state === "idle") return;

  if (state === "drawing") {
    const x = e.clientX;
    const y = e.clientY;

    // Sample the straight segment between the last mouse position and the
    // current one. Each sample looks for a grapheme under it; only those
    // chars get added to visitedChars. This is what makes "diagonal jumps
    // across line wraps" stop auto-underlining text the cursor never touched.
    const dx = x - session.prevX;
    const dy = y - session.prevY;
    const dist = Math.hypot(dx, dy);
    const steps = Math.max(1, Math.ceil(dist / 2));
    for (let i = 1; i <= steps; i++) {
      const t = i / steps;
      const px = session.prevX + dx * t;
      const py = session.prevY + dy * t;
      const hit = getCursorFromPoint(px, py);
      if (hit && hit.paragraphId === session.paragraphId) {
        session.visitedChars.add(hit.charIndex);
      }
    }
    session.prevX = x;
    session.prevY = y;

    // Chain rule: extend chain outward only through chars adjacent to current
    // ends. Visited chars far from the chain stay "stranded" — they don't
    // underline until the gap between them and the chain is filled.
    let lo = session.chainLo;
    let hi = session.chainHi;
    while (session.visitedChars.has(lo - 1)) lo--;
    while (session.visitedChars.has(hi + 1)) hi++;
    session.chainLo = lo;
    session.chainHi = hi;

    applyUnderline();

    if (!isInsideParagraphRect(session.paragraphEl, x, y)) {
      enterTransitioning(e);
    }
    return;
  }

  if (state === "transitioning" || state === "annotating") {
    session.lastMoveT = performance.now();
    updateFlowingPath(e.clientX, e.clientY);
    if (state === "transitioning") {
      // Reset idle timer; if cursor is still long enough → annotation
      if (session.idleTimer) clearTimeout(session.idleTimer);
      session.idleTimer = setTimeout(
        () => maybeOpenAnnotation(e.clientX, e.clientY),
        ANNOTATE_DELAY_MS,
      );
    }
  }
}

function onMouseUp(_e) {
  if (state === "drawing") {
    finishUnderline();
  }
  // In transitioning/annotating, mouseup doesn't end things — we wait for
  // the cursor to rest (transition→annotate) or Enter/blur (annotate→idle).
}

// ---------- drawing phase ----------

function applyUnderline() {
  const lo = session.chainLo;
  const hi = session.chainHi;
  const para = session.paragraphEl;
  const spans = para.querySelectorAll("[data-char-index]");

  // Two-pass: collect spans newly entering the range, then apply one shared
  // thickness derived from the batch's avg time-per-char (slower = thicker).
  const newSpans = [];
  for (const s of spans) {
    const i = Number(s.dataset.charIndex);
    const want = i >= lo && i <= hi;
    if (want) {
      if (!s.classList.contains("is-underlined")) newSpans.push(s);
    } else if (s.classList.contains("is-underlined")) {
      s.classList.remove("is-underlined");
      s.style.removeProperty("--underline-thickness");
      session.underlinedSpans.delete(i);
    }
  }

  if (newSpans.length === 0) return;

  const now = performance.now();
  const dt = now - session.lastAddT;
  const dtPerChar = dt / newSpans.length;
  // 5ms/char → 1.5px (sweeping fast), 100ms/char → 4.5px (deliberate)
  const norm = Math.min(Math.max((dtPerChar - 5) / 95, 0), 1);
  const thickness = (1.5 + norm * 3).toFixed(2);
  session.lastAddT = now;

  for (const s of newSpans) {
    s.style.setProperty("--underline-thickness", `${thickness}px`);
    s.classList.add("is-underlined");
    session.underlinedSpans.add(Number(s.dataset.charIndex));
  }
}

function finishUnderline() {
  const lo = session.chainLo;
  const hi = session.chainHi;
  const text = readSelectedText(session.paragraphId, lo, hi + 1);
  const endTime = performance.now();
  const duration = endTime - session.startTime;
  const len = Math.max(0, hi - lo + 1);
  pushSignal({
    type: "highlight_underline",
    highlight_session_id: session.id,
    paragraph_id: session.paragraphId,
    selected_text: text,
    start_cursor: charIndexToCursor(session.paragraphId, lo),
    end_cursor: charIndexToCursor(session.paragraphId, hi),
    char_range: [lo, hi],
    start_t: session.startTime,
    end_t: endTime,
    duration_ms: Math.round(duration),
    text_length: len,
    draw_speed: duration > 0 ? +(len / (duration / 1000)).toFixed(2) : 0,
  });
  // Convert the active underline to the persistent faded "annotated" state
  // instead of wiping it — every drawn underline leaves a quiet trace.
  freezeUnderline();
  state = "idle";
  session = null;
  setTrailEnabled(true);
  setGesturesEnabled(true);
}

// ---------- transition phase ----------

function enterTransitioning(e) {
  state = "transitioning";

  // Underline range = current chain (the contiguous run of chars whose
  // cursor path actually crossed them starting from startChar).
  const lo = session.chainLo;
  const hi = session.chainHi;

  // Anchor describes exactly what was underlined — no expansion to word
  // boundaries, no "last 3 words" cap. The circle hugs the chain itself.
  const text = readSelectedText(session.paragraphId, lo, hi + 1);
  session.anchorWord = {
    paragraphId: session.paragraphId,
    text,
    startChar: lo,
    endChar: hi + 1,
    startCursor: charIndexToCursor(session.paragraphId, lo),
  };

  // Push the underline signal that ended at paragraph exit so the
  // sequence (underline → annotation) is paired by session id.
  const transitionT = performance.now();
  session.transitionT = transitionT;
  pushSignal({
    type: "highlight_underline",
    highlight_session_id: session.id,
    paragraph_id: session.paragraphId,
    selected_text: text,
    start_cursor: charIndexToCursor(session.paragraphId, lo),
    end_cursor: charIndexToCursor(session.paragraphId, hi),
    char_range: [lo, hi],
    start_t: session.startTime,
    end_t: transitionT,
    duration_ms: Math.round(transitionT - session.startTime),
    text_length: hi - lo + 1,
    draw_speed:
      transitionT - session.startTime > 0
        ? +((hi - lo + 1) / ((transitionT - session.startTime) / 1000)).toFixed(2)
        : 0,
    exited_paragraph: true,
  });

  // Anchor circle wraps the entire chain bbox.
  const bbox = getCharRangeBBox(session.paragraphId, lo, hi + 1);
  if (bbox) {
    drawAnchorCircle(bbox);
  }

  // Keep the underline visible alongside the circle — it stays through the
  // annotation phase and is converted to a faded "annotated" state on confirm.

  // Start the ink path; updateFlowingPath recomputes it from anchor → cursor each move.
  startInkPath();
  updateFlowingPath(e.clientX, e.clientY);
}

function drawAnchorCircle(bbox) {
  const PAD_X = 10;
  const PAD_Y = 7;
  const cx = bbox.left + bbox.width / 2;
  const cy = bbox.top + bbox.height / 2;
  const rx = bbox.width / 2 + PAD_X;
  const ry = bbox.height / 2 + PAD_Y;

  // Ramanujan approximation of ellipse perimeter — used to drive the
  // stroke-dasharray "pen is drawing the circle" animation.
  const h = ((rx - ry) / (rx + ry)) ** 2;
  const perimeter =
    Math.PI * (rx + ry) * (1 + (3 * h) / (10 + Math.sqrt(4 - 3 * h)));

  const ell = document.createElementNS(SVG_NS, "ellipse");
  ell.setAttribute("class", "anchor-circle");
  ell.setAttribute("cx", cx.toFixed(1));
  ell.setAttribute("cy", cy.toFixed(1));
  ell.setAttribute("rx", rx.toFixed(1));
  ell.setAttribute("ry", ry.toFixed(1));
  // Slight tilt for hand-drawn pen feel.
  ell.setAttribute("transform", `rotate(-5, ${cx.toFixed(1)}, ${cy.toFixed(1)})`);
  ell.style.strokeDasharray = perimeter.toFixed(1);
  ell.style.strokeDashoffset = perimeter.toFixed(1);
  ell.style.transition = "stroke-dashoffset 0.8s ease-out";

  inkLayer.appendChild(ell);

  // Two rAFs so the transition reliably fires (skipping just one is racy on
  // some browsers when the element was just appended).
  requestAnimationFrame(() =>
    requestAnimationFrame(() => {
      ell.style.strokeDashoffset = "0";
    }),
  );

  session.anchorCircle = ell;
  session.anchorCenter = { x: cx, y: cy, rx, ry };
}

function startInkPath() {
  const path = document.createElementNS(SVG_NS, "path");
  path.setAttribute("class", "ink-stroke");
  inkLayer.appendChild(path);
  session.inkPath = path;
}

// Single cubic Bezier from the anchor ellipse edge to the cursor, recomputed
// every move. No point accumulation → no trailing build-up, always smooth.
// Matches the original prototype's updateFlowingPath geometry.
function updateFlowingPath(cursorX, cursorY) {
  if (!session || !session.inkPath || !session.anchorCenter) return;
  const { x: cx, y: cy, rx, ry } = session.anchorCenter;
  const dx = cursorX - cx;
  const dy = cursorY - cy;
  // Start point: ellipse edge in the cursor's direction.
  const angle = Math.atan2(dy * rx, dx * ry);
  const sx = cx + rx * Math.cos(angle);
  const sy = cy + ry * Math.sin(angle);
  // Slight downward droop — like ink trailing under its own weight.
  const dist = Math.hypot(dx, dy);
  const droop = Math.min(dist * 0.12, 24);
  const cp1x = sx + dx * 0.3;
  const cp1y = sy + dy * 0.3 + droop;
  const cp2x = cursorX - dx * 0.12;
  const cp2y = cursorY - dy * 0.08 + droop * 0.4;
  session.inkPath.setAttribute(
    "d",
    `M ${sx.toFixed(1)} ${sy.toFixed(1)} C ${cp1x.toFixed(1)} ${cp1y.toFixed(1)} ${cp2x.toFixed(1)} ${cp2y.toFixed(1)} ${cursorX.toFixed(1)} ${cursorY.toFixed(1)}`,
  );
}

// ---------- annotation phase ----------

function maybeOpenAnnotation(x, y) {
  if (state !== "transitioning") return;
  state = "annotating";
  session.textareaAppearedT = performance.now();
  setTrailEnabled(false);

  const box = document.createElement("div");
  box.className = "annotation-box";
  box.style.left = `${x + 12}px`;
  box.style.top = `${y + 12}px`;

  const ta = document.createElement("textarea");
  ta.placeholder = "주석을 적어주세요…";
  ta.rows = 2;
  box.appendChild(ta);

  const hint = document.createElement("div");
  hint.className = "hint";
  hint.textContent = "Enter 로 확정 · Esc 로 취소";
  box.appendChild(hint);

  annotationHost.appendChild(box);
  session.annotationBox = box;

  ta.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      confirmAnnotation(ta.value.trim());
    } else if (e.key === "Escape") {
      e.preventDefault();
      cancelAnnotation();
    }
  });
  ta.addEventListener("blur", () => {
    // small delay so clicks inside the box don't immediately blur it
    setTimeout(() => {
      if (state === "annotating" && document.activeElement !== ta) {
        const v = ta.value.trim();
        if (v) confirmAnnotation(v);
        else cancelAnnotation();
      }
    }, 120);
  });

  // focus on next frame so the animation runs first
  requestAnimationFrame(() => ta.focus());
}

function confirmAnnotation(textValue) {
  if (state !== "annotating" || !session) return;
  const confirmT = performance.now();
  const word = session.anchorWord;

  pushSignal({
    type: "highlight_annotation",
    highlight_session_id: session.id,
    paragraph_id: session.paragraphId,
    anchor_text: word ? word.text : "",
    anchor_cursor: word ? word.startCursor : null,
    annotation_text: textValue,
    underline_start_t: session.startTime,
    transition_t: session.transitionT,
    textarea_appeared_t: session.textareaAppearedT,
    confirm_t: confirmT,
    total_duration_ms: Math.round(confirmT - session.startTime),
  });

  // Convert the live underline into a permanent faded "annotated" state
  // before cleanup wipes the live classes — preserves the visible record.
  freezeUnderline();

  // Leave a small marker on the anchor word's right edge.
  if (word) {
    placeAnnotationMarker(word, textValue);
  }

  cleanupSession();
}

function freezeUnderline() {
  if (!session || !session.paragraphEl) return;
  const para = session.paragraphEl;
  const lo = session.chainLo;
  const hi = session.chainHi;
  for (let i = lo; i <= hi; i++) {
    const span = para.querySelector(`[data-char-index="${i}"]`);
    if (!span) continue;
    if (span.classList.contains("is-underlined")) {
      span.classList.remove("is-underlined");
      span.classList.add("is-annotated");
    }
  }
  // Once frozen, cleanupSession's resetUnderlineClasses (which only targets
  // .is-underlined) will leave these alone.
}

function cancelAnnotation() {
  cleanupSession();
}

function placeAnnotationMarker(word, text) {
  const para = document.querySelector(
    `[data-paragraph-id="${word.paragraphId}"]`,
  );
  if (!para) return;
  const lastSpan = para.querySelector(
    `[data-char-index="${word.endChar - 1}"]`,
  );
  if (!lastSpan) return;

  const marker = document.createElement("span");
  marker.className = "anno-marker";
  marker.setAttribute("tabindex", "0");

  const tooltip = document.createElement("span");
  tooltip.className = "anno-tooltip";
  tooltip.textContent = text;
  marker.appendChild(tooltip);

  // Inline sibling right after the anchor word — flows with text, never overlaps.
  lastSpan.after(marker);
}

// ---------- helpers ----------

function cleanupSession() {
  setTrailEnabled(true);
  setGesturesEnabled(true);
  if (!session) {
    state = "idle";
    return;
  }
  if (session.idleTimer) clearTimeout(session.idleTimer);
  if (session.anchorCircle) session.anchorCircle.remove();
  if (session.inkPath) session.inkPath.remove();
  if (session.annotationBox) session.annotationBox.remove();
  resetUnderlineClasses();
  session = null;
  state = "idle";
}

function resetUnderlineClasses() {
  if (!session) return;
  const para = session.paragraphEl;
  if (!para) return;
  for (const s of para.querySelectorAll(".is-underlined")) {
    s.classList.remove("is-underlined");
    s.style.removeProperty("--underline-thickness");
  }
  session.underlinedSpans.clear?.();
}

function readSelectedText(paragraphId, startChar, endCharExclusive) {
  const para = document.querySelector(`[data-paragraph-id="${paragraphId}"]`);
  if (!para) return "";
  let out = "";
  for (let i = startChar; i < endCharExclusive; i++) {
    const sp = para.querySelector(`[data-char-index="${i}"]`);
    if (sp) out += sp.textContent;
  }
  return out;
}

function isInsideParagraphRect(paraEl, x, y) {
  if (!paraEl) return false;
  const r = paraEl.getBoundingClientRect();
  // small tolerance so the very edge doesn't trigger transition prematurely
  const pad = 2;
  return (
    x >= r.left - pad &&
    x <= r.right + pad &&
    y >= r.top - pad &&
    y <= r.bottom + pad
  );
}

function uuid() {
  if (crypto.randomUUID) return crypto.randomUUID();
  return "h-" + Math.random().toString(36).slice(2) + Date.now().toString(36);
}
