// highlight.js
// The highlighting interaction: dragging across text draws an underline;
// when the cursor leaves the paragraph mid-stroke, the last underlined word
// becomes a circle and a stroke flows out toward the cursor; if the cursor
// then rests, an annotation textarea appears.
//
// State machine:
//   idle → drawing            (mousedown on a grapheme span)
//   drawing → drawing         (mousemove inside same paragraph)
//   drawing → idle            (mouseup → push underline signal)
//   drawing → transitioning   (mousemove leaves the paragraph rect)
//   transitioning → annotating(cursor still ~600ms → textarea appears)
//   annotating → idle         (Enter or blur → push annotation signal)
//
// Same-session continuity: underline and annotation generated by one drag
// share the same highlight_session_id so AI can read the sequence as a unit.

import { pushSignal } from "./signals.js";
import {
  getCursorFromPoint,
  charIndexToCursor,
  getWordRangeAt,
  getCharRangeBBox,
} from "./pretext_helpers.js";

const SVG_NS = "http://www.w3.org/2000/svg";
const ANNOTATE_DELAY_MS = 600;

let state = "idle";
let session = null;
let inkLayer = null;
let annotationHost = null;

export function initHighlight() {
  inkLayer = document.getElementById("ink-layer");
  annotationHost = document.getElementById("annotation-host");
  if (!inkLayer || !annotationHost) return;

  document.addEventListener("mousedown", onMouseDown);
  document.addEventListener("mousemove", onMouseMove);
  document.addEventListener("mouseup", onMouseUp);
  // Defensive: if the window loses focus mid-drag, drop state cleanly.
  window.addEventListener("blur", () => {
    if (state === "drawing") finishUnderline();
    else if (state !== "idle") cleanupSession();
  });
}

// ---------- mouse handlers ----------

function onMouseDown(e) {
  if (state !== "idle") return;
  if (e.button !== 0) return;
  const target = e.target;
  if (!(target instanceof Element)) return;
  if (!target.closest("[data-char-index]")) return;
  // Don't start when clicking inside an open annotation, toolbar, dashboard.
  if (target.closest(".annotation-box, .toolbar, .dashboard")) return;

  const hit = getCursorFromPoint(e.clientX, e.clientY);
  if (!hit) return;

  const id = uuid();
  session = {
    id,
    paragraphId: hit.paragraphId,
    paragraphEl: document.querySelector(
      `[data-paragraph-id="${hit.paragraphId}"]`,
    ),
    startChar: hit.charIndex,
    endChar: hit.charIndex,
    minChar: hit.charIndex,
    maxChar: hit.charIndex,
    startCursor: hit.cursor,
    startTime: performance.now(),
    underlinedSpans: new Set(),
    // transition / annotation phase state
    anchorCircle: null,
    inkPath: null,
    inkPoints: [],
    transitionT: 0,
    lastMoveT: 0,
    idleTimer: null,
    annotationBox: null,
    textareaAppearedT: 0,
    anchorWord: null,
  };
  state = "drawing";
  applyUnderline();
  e.preventDefault();
}

function onMouseMove(e) {
  if (state === "idle") return;

  if (state === "drawing") {
    const hit = getCursorFromPoint(e.clientX, e.clientY);
    if (
      hit &&
      hit.paragraphId === session.paragraphId &&
      isInsideParagraphRect(session.paragraphEl, e.clientX, e.clientY)
    ) {
      session.endChar = hit.charIndex;
      if (hit.charIndex < session.minChar) session.minChar = hit.charIndex;
      if (hit.charIndex > session.maxChar) session.maxChar = hit.charIndex;
      applyUnderline();
    } else if (
      !isInsideParagraphRect(session.paragraphEl, e.clientX, e.clientY)
    ) {
      enterTransitioning(e);
    }
    return;
  }

  if (state === "transitioning" || state === "annotating") {
    session.lastMoveT = performance.now();
    pushInkPoint(e.clientX, e.clientY);
    if (state === "transitioning") {
      // Reset idle timer; if cursor is still long enough → annotation
      if (session.idleTimer) clearTimeout(session.idleTimer);
      session.idleTimer = setTimeout(
        () => maybeOpenAnnotation(e.clientX, e.clientY),
        ANNOTATE_DELAY_MS,
      );
    }
  }
}

function onMouseUp(_e) {
  if (state === "drawing") {
    finishUnderline();
  }
  // In transitioning/annotating, mouseup doesn't end things — we wait for
  // the cursor to rest (transition→annotate) or Enter/blur (annotate→idle).
}

// ---------- drawing phase ----------

function applyUnderline() {
  const lo = Math.min(session.startChar, session.endChar);
  const hi = Math.max(session.startChar, session.endChar);
  const para = session.paragraphEl;
  const spans = para.querySelectorAll("[data-char-index]");
  for (const s of spans) {
    const i = Number(s.dataset.charIndex);
    const want = i >= lo && i <= hi;
    if (want) {
      if (!s.classList.contains("is-underlined")) {
        s.classList.add("is-underlined");
        session.underlinedSpans.add(i);
      }
    } else if (s.classList.contains("is-underlined")) {
      s.classList.remove("is-underlined");
      session.underlinedSpans.delete(i);
    }
  }
}

function finishUnderline() {
  const lo = Math.min(session.startChar, session.endChar);
  const hi = Math.max(session.startChar, session.endChar);
  const text = readSelectedText(session.paragraphId, lo, hi + 1);
  const endTime = performance.now();
  const duration = endTime - session.startTime;
  const len = Math.max(0, hi - lo + 1);
  pushSignal({
    type: "highlight_underline",
    highlight_session_id: session.id,
    paragraph_id: session.paragraphId,
    selected_text: text,
    start_cursor: charIndexToCursor(session.paragraphId, lo),
    end_cursor: charIndexToCursor(session.paragraphId, hi),
    char_range: [lo, hi],
    start_t: session.startTime,
    end_t: endTime,
    duration_ms: Math.round(duration),
    text_length: len,
    draw_speed: duration > 0 ? +(len / (duration / 1000)).toFixed(2) : 0,
  });
  resetUnderlineClasses();
  state = "idle";
  session = null;
}

// ---------- transition phase ----------

function enterTransitioning(e) {
  state = "transitioning";

  // Pick the anchor: the last word that was underlined.
  const anchorChar =
    session.maxChar !== undefined ? session.maxChar : session.endChar;
  const word = getWordRangeAt(session.paragraphId, anchorChar);
  session.anchorWord = word;

  // Push the underline signal that ended at paragraph exit so the
  // sequence (underline → annotation) is paired by session id.
  const lo = Math.min(session.startChar, session.endChar);
  const hi = Math.max(session.startChar, session.endChar);
  const text = readSelectedText(session.paragraphId, lo, hi + 1);
  const transitionT = performance.now();
  session.transitionT = transitionT;
  pushSignal({
    type: "highlight_underline",
    highlight_session_id: session.id,
    paragraph_id: session.paragraphId,
    selected_text: text,
    start_cursor: charIndexToCursor(session.paragraphId, lo),
    end_cursor: charIndexToCursor(session.paragraphId, hi),
    char_range: [lo, hi],
    start_t: session.startTime,
    end_t: transitionT,
    duration_ms: Math.round(transitionT - session.startTime),
    text_length: hi - lo + 1,
    draw_speed:
      transitionT - session.startTime > 0
        ? +((hi - lo + 1) / ((transitionT - session.startTime) / 1000)).toFixed(2)
        : 0,
    exited_paragraph: true,
  });

  // Render the anchor circle around the chosen word.
  if (word) {
    const bbox = getCharRangeBBox(session.paragraphId, word.startChar, word.endChar);
    if (bbox) {
      drawAnchorCircle(bbox);
    }
  }

  // Drop the visible per-char underlines (anchor circle now represents the trace).
  resetUnderlineClasses();

  // Start the ink path with current cursor as origin.
  startInkPath(e.clientX, e.clientY);
  pushInkPoint(e.clientX, e.clientY);
}

function drawAnchorCircle(bbox) {
  const cx = bbox.left + bbox.width / 2;
  const cy = bbox.top + bbox.height / 2;
  const r = Math.max(bbox.width, bbox.height) * 0.7 + 4;

  // Start as a flat ellipse hugging the underline shape, then expand to a circle.
  const startRx = bbox.width / 2 + 2;
  const startRy = 2.5;

  const ell = document.createElementNS(SVG_NS, "ellipse");
  ell.setAttribute("class", "anchor-circle");
  ell.setAttribute("cx", String(cx));
  ell.setAttribute("cy", String(bbox.bottom + 2));
  ell.setAttribute("rx", String(startRx));
  ell.setAttribute("ry", String(startRy));
  inkLayer.appendChild(ell);

  // Force a tick, then animate to the rounder shape.
  requestAnimationFrame(() => {
    ell.setAttribute("cy", String(cy));
    ell.setAttribute("rx", String(r));
    ell.setAttribute("ry", String(r * 0.65));
    ell.style.transition =
      "all 0.8s cubic-bezier(0.2, 0.7, 0.2, 1)";
  });

  session.anchorCircle = ell;
  session.anchorCenter = { x: cx, y: cy, r };
}

function startInkPath(x, y) {
  const path = document.createElementNS(SVG_NS, "path");
  path.setAttribute("class", "ink-stroke");
  inkLayer.appendChild(path);
  session.inkPath = path;
  // Seed the path from the anchor circle edge if available, else from cursor.
  if (session.anchorCenter) {
    const ax = session.anchorCenter.x;
    const ay = session.anchorCenter.y;
    session.inkPoints = [{ x: ax, y: ay }, { x, y }];
  } else {
    session.inkPoints = [{ x, y }];
  }
  redrawInkPath();
}

function pushInkPoint(x, y) {
  if (!session || !session.inkPath) return;
  const last = session.inkPoints[session.inkPoints.length - 1];
  if (last && Math.hypot(x - last.x, y - last.y) < 2) return;
  session.inkPoints.push({ x, y });
  redrawInkPath();
}

function redrawInkPath() {
  if (!session || !session.inkPath || !session.inkPoints.length) return;
  const pts = session.inkPoints;
  let d = `M ${pts[0].x} ${pts[0].y}`;
  for (let i = 1; i < pts.length; i++) {
    const p = pts[i];
    const prev = pts[i - 1];
    const mx = (p.x + prev.x) / 2;
    const my = (p.y + prev.y) / 2;
    d += ` Q ${prev.x} ${prev.y} ${mx} ${my}`;
  }
  session.inkPath.setAttribute("d", d);
}

// ---------- annotation phase ----------

function maybeOpenAnnotation(x, y) {
  if (state !== "transitioning") return;
  state = "annotating";
  session.textareaAppearedT = performance.now();

  const box = document.createElement("div");
  box.className = "annotation-box";
  box.style.left = `${x + 12}px`;
  box.style.top = `${y + 12}px`;

  const ta = document.createElement("textarea");
  ta.placeholder = "주석을 적어주세요…";
  ta.rows = 2;
  box.appendChild(ta);

  const hint = document.createElement("div");
  hint.className = "hint";
  hint.textContent = "Enter 로 확정 · Esc 로 취소";
  box.appendChild(hint);

  annotationHost.appendChild(box);
  session.annotationBox = box;

  ta.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      confirmAnnotation(ta.value.trim());
    } else if (e.key === "Escape") {
      e.preventDefault();
      cancelAnnotation();
    }
  });
  ta.addEventListener("blur", () => {
    // small delay so clicks inside the box don't immediately blur it
    setTimeout(() => {
      if (state === "annotating" && document.activeElement !== ta) {
        const v = ta.value.trim();
        if (v) confirmAnnotation(v);
        else cancelAnnotation();
      }
    }, 120);
  });

  // focus on next frame so the animation runs first
  requestAnimationFrame(() => ta.focus());
}

function confirmAnnotation(textValue) {
  if (state !== "annotating" || !session) return;
  const confirmT = performance.now();
  const word = session.anchorWord;

  pushSignal({
    type: "highlight_annotation",
    highlight_session_id: session.id,
    paragraph_id: session.paragraphId,
    anchor_text: word ? word.text : "",
    anchor_cursor: word ? word.startCursor : null,
    annotation_text: textValue,
    underline_start_t: session.startTime,
    transition_t: session.transitionT,
    textarea_appeared_t: session.textareaAppearedT,
    confirm_t: confirmT,
    total_duration_ms: Math.round(confirmT - session.startTime),
  });

  // Leave a small marker on the anchor word's right edge.
  if (word) {
    placeAnnotationMarker(word, textValue);
  }

  cleanupSession();
}

function cancelAnnotation() {
  cleanupSession();
}

function placeAnnotationMarker(word, text) {
  const para = document.querySelector(
    `[data-paragraph-id="${word.paragraphId}"]`,
  );
  if (!para) return;
  const lastSpan = para.querySelector(
    `[data-char-index="${word.endChar - 1}"]`,
  );
  if (!lastSpan) return;
  const r = lastSpan.getBoundingClientRect();
  const pr = para.getBoundingClientRect();
  const dot = document.createElement("span");
  dot.className = "anno-marker";
  dot.dataset.text = text;
  dot.style.left = `${r.right - pr.left + 6}px`;
  dot.style.top = `${r.top + r.height / 2 - pr.top}px`;
  para.appendChild(dot);
}

// ---------- helpers ----------

function cleanupSession() {
  if (!session) {
    state = "idle";
    return;
  }
  if (session.idleTimer) clearTimeout(session.idleTimer);
  if (session.anchorCircle) session.anchorCircle.remove();
  if (session.inkPath) session.inkPath.remove();
  if (session.annotationBox) session.annotationBox.remove();
  resetUnderlineClasses();
  session = null;
  state = "idle";
}

function resetUnderlineClasses() {
  if (!session) return;
  const para = session.paragraphEl;
  if (!para) return;
  for (const s of para.querySelectorAll(".is-underlined")) {
    s.classList.remove("is-underlined");
  }
  session.underlinedSpans.clear?.();
}

function readSelectedText(paragraphId, startChar, endCharExclusive) {
  const para = document.querySelector(`[data-paragraph-id="${paragraphId}"]`);
  if (!para) return "";
  let out = "";
  for (let i = startChar; i < endCharExclusive; i++) {
    const sp = para.querySelector(`[data-char-index="${i}"]`);
    if (sp) out += sp.textContent;
  }
  return out;
}

function isInsideParagraphRect(paraEl, x, y) {
  if (!paraEl) return false;
  const r = paraEl.getBoundingClientRect();
  // small tolerance so the very edge doesn't trigger transition prematurely
  const pad = 2;
  return (
    x >= r.left - pad &&
    x <= r.right + pad &&
    y >= r.top - pad &&
    y <= r.bottom + pad
  );
}

function uuid() {
  if (crypto.randomUUID) return crypto.randomUUID();
  return "h-" + Math.random().toString(36).slice(2) + Date.now().toString(36);
}
